# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='descricao',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
