# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificado', '0002_evento_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='name',
            new_name='nome',
        ),
    ]
