# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificado', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='numero',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
